kind: functionapp
identity:
  userAssignedIdentities:
    "/subscriptions/<SUBSCRIPTION_ID>/resourcegroups/<RESOURCE_GROUOP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<USER_NAME>": {}
  type: UserAssigned
properties:
  # same as regular container app properties
